sudo: required
language: generic

matrix:
  include:
# Makefile builder
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: BUILDER=make DISTRO=native LANGUAGE=cc
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: BUILDER=make DISTRO=native LANGUAGE=python

    - os: osx
      language: cpp
      compiler: clang
      env: BUILDER=make DISTRO=native LANGUAGE=cc
    - os: osx
      language: cpp
      compiler: clang
      env: BUILDER=make DISTRO=native LANGUAGE=python
# CMake Build Generator
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: BUILDER=cmake DISTRO=native
    - os: linux
      dist: trusty
      language: cpp
      compiler: clang
      env: BUILDER=cmake DISTRO=native

    - os: osx
      language: cpp
      compiler: gcc
      env: BUILDER=cmake DISTRO=native
    - os: osx
      language: cpp
      compiler: clang
      env: BUILDER=cmake DISTRO=native

install:
  - ./.travis/install.sh

script:
  - ./.travis/script.sh
