sudo: required
language: generic

matrix:
  include:
# Makefile builder
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: BUILDER=make DISTRO=native LANGUAGE=cc
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: BUILDER=make DISTRO=native LANGUAGE=python2
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: BUILDER=make DISTRO=native LANGUAGE=python3
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: BUILDER=make DISTRO=native LANGUAGE=java
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: BUILDER=make DISTRO=native LANGUAGE=dotnet

    - os: osx
      osx_image: xode9.4
      language: cpp
      compiler: clang
      env: BUILDER=make DISTRO=native LANGUAGE=cc
    - os: osx
      osx_image: xode9.4
      language: cpp
      compiler: clang
      env: BUILDER=make DISTRO=native LANGUAGE=python2
    - os: osx
      osx_image: xode9.4
      language: cpp
      compiler: clang
      env: BUILDER=make DISTRO=native LANGUAGE=python3
    - os: osx
      osx_image: xode9.4
      language: cpp
      compiler: clang
      env: BUILDER=make DISTRO=native LANGUAGE=java
    - os: osx
      osx_image: xode9.4
      language: cpp
      compiler: clang
      env: BUILDER=make DISTRO=native LANGUAGE=dotnet
# CMake Build Generator
    - os: linux
      dist: trusty
      language: cpp
      compiler: gcc
      env: BUILDER=cmake DISTRO=native
    - os: linux
      dist: trusty
      language: cpp
      compiler: clang
      env: BUILDER=cmake DISTRO=native

    - os: osx
      osx_image: xode9.4
      language: cpp
      compiler: gcc
      env: BUILDER=cmake DISTRO=native
    - os: osx
      osx_image: xode9.4
      language: cpp
      compiler: clang
      env: BUILDER=cmake DISTRO=native

install:
  - ./.travis/install.sh

script:
  - ./.travis/script.sh
