name = "ORTools"
uuid = "b7d69b34-a827-4671-8cfa-f7e1eec930c7"
version = "0.0.1"

[deps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
ORTools_jll = "717719f8-c30c-5086-8f3c-70cd6a1e3a46"
ORToolsGenerated = "6b269722-41d3-11ee-be56-0242ac120002"
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.9"
ORTools_jll = "9.14.0"
ORToolsGenerated = "0.0.2"
ProtoBuf = "1.0.15"
MathOptInterface = "1.42.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
