name: amd64 Windows Make Python

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  make:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install python3
      run: python3 -m pip install --user mypy-protobuf absl-py setuptools wheel numpy pandas
    - name: Check make
      run: tools\make --version
    - name: Check system
      run: tools\make detect_port
    - name: Check Python
      run: tools\make detect_python
    - name: Build C++ and Python
      run: tools\make python JOBS=4
    - name: Test Python
      run: tools\make test_python
    - name: Create wheel package
      run: tools\make package_python
