name: amd64 Windows Make Java

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  make:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Check java
      run: java -version
    - name: Check make
      run: tools\make --version
    - name: Check system
      run: tools\make detect_port
    - name: Check Java
      run: tools\make detect_java
    - name: Build C++ and Java
      run: tools\make java JOBS=4
    - name: Test Java
      run: tools\make test_java -j4
    - name: Create maven package
      run: tools\make package_java
