name: amd64 Linux Make C++

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  make:
    runs-on: ubuntu-latest
    env:
      CC:  gcc-10
      CXX: g++-10
    steps:
    - uses: actions/checkout@v3
    - name: Check make
      run: make --version
    - name: Check system
      run: make detect_port
    - name: Check C++
      run: make detect_cpp
    - name: Build C++
      run: make cpp JOBS=4
    - name: Test C++
      run: make test_cpp
    - name: Create archive
      run: make archive_cpp
