name: amd64 Linux Make Python

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  make:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update Path
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Install python3
      run: |
        sudo apt-get install python3-venv python3-pip
        python3 -m pip install --user mypy-protobuf absl-py numpy pandas
    - name: Swig install
      run: sudo apt install -y swig
    - name: Check swig
      run: swig -version
    - name: Check make
      run: make --version
    - name: Check system
      run: make detect_port
    - name: Check Python
      run: make detect_python
    - name: Build C++ and Python
      run: make python JOBS=4
    - name: Test Python
      run: make test_python -j4
    - name: Create wheel package
      run: make package_python
