name: CMake linux

on: workflow_dispatch

jobs:
  cmake:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Pip install reqs
        run: python3 -m pip install --user mypy-protobuf absl-py setuptools wheel numpy pandas virtualenv
      - name: Checkout Sirius repo
        uses: actions/checkout@v2
        with:
          repository: rte-france/sirius-solver
          path: ./sirius-solver
          ref: antares_integration
      - name: Configure Sirius
        working-directory: ./sirius-solver
        run: |
          cmake -S src \
                -B build \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX=SiriusInstall
      - name: Build & Install Sirius
        working-directory: ./sirius-solver
        run: cmake --build build/ --config Release --target install -j14
      - name: Upload sirius lib
        uses: actions/upload-artifact@v2
        with:
          name: sirius_solver
          path: ./sirius-solver/SiriusInstall/lib/libsirius_solver.so
      - name: Checkout xpressmp813
        uses: actions/checkout@v2
        with:
          repository: jdarlay/xpressmp813Lin
          path: ./xpressmp813
          ref: master
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Checkout or-tools
        uses: actions/checkout@v2
        with:
          path: ./or-tools
      - name: Configure or-tools
        working-directory: ./or-tools
        run: |
          cmake -S. \
                -Bbuild \
                -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_DEPS=ON \
                -DUSE_SIRIUS=ON \
                -Dsirius_solver_DIR="${{ github.workspace }}/sirius-solver/SiriusInstall/cmake" \
                -DUSE_XPRESS=ON \
                -DXPRESS_ROOT="${{ github.workspace }}/xpressmp813" \
                -DBUILD_PYTHON=ON \
                -DBUILD_JAVA=ON \
                -DBUILD_DOTNET=ON
      - name: Build tests
        working-directory: ./or-tools
        run: |
          cmake --build build \
                --target linear_programming \
                         sirius_interface \
                         xpress_interface \
                         python_package \
                         java_package \
                         java_example_LinearProgramming \
                         dotnet_package \
                         dotnet_example_cslinearprogramming \
                -j14
      - name: Upload libortools
        uses: actions/upload-artifact@v2
        with:
          name: libortools
          path: ./or-tools/build/lib/libortools.so
      - name: Upload ortools wheel
        uses: actions/upload-artifact@v2
        with:
          name: ortools_wheel
          path: './or-tools/build/python/dist/*.whl'
      - name: Upload ortools jar
        uses: actions/upload-artifact@v2
        with:
          name: ortools_jar
          path: './or-tools/build/java/ortools-java/target/*.jar'
      - name: Upload ortools dotnet
        uses: actions/upload-artifact@v2
        with:
          name: ortools_dotnet
          path: |
            ./or-tools/build/dotnet/packages/Google.OrTools.[0-9]*.[0-9]*.[0-9]*.nupkg
            ./or-tools/build/dotnet/packages/Google.OrTools.runtime.*.[0-9]*.[0-9]*.[0-9]*.nupkg
      - name: Run sirius_interface unittests
        id: sirius_interface_unittests
        continue-on-error: true
        working-directory: ./or-tools/build
        run: ctest -V -R 'cxx_unittests_sirius_interface'
        env:
          LD_LIBRARY_PATH: "${{ github.workspace }}/sirius-solver/SiriusInstall/lib/:${{ github.workspace }}/xpressmp813/lib/"
      - name: Run xpress_interface unittests
        id: xpress_interface_unittests
        continue-on-error: true
        working-directory: ./or-tools/build
        run: ctest -V -R 'cxx_unittests_xpress_interface'
        env:
          LD_LIBRARY_PATH: "${{ github.workspace }}/sirius-solver/SiriusInstall/lib/:${{ github.workspace }}/xpressmp813/lib/"
      - name: Run cpp tests
        id: cpp_tests
        continue-on-error: true
        working-directory: ./or-tools/build
        run: ctest -V -R cxx_cpp_linear_programming
        env:
          LD_LIBRARY_PATH: "${{ github.workspace }}/sirius-solver/SiriusInstall/lib/:${{ github.workspace }}/xpressmp813/lib/"
      - name: Run python tests
        id: python_tests
        continue-on-error: true
        working-directory: ./or-tools/build
        run: ctest -V -R python_python_linear_programming_sirius_xpress
        env:
          LD_LIBRARY_PATH: "${{ github.workspace }}/sirius-solver/SiriusInstall/lib/:${{ github.workspace }}/xpressmp813/lib/"
      - name: Run java tests
        id: java_tests
        continue-on-error: true
        working-directory: ./or-tools/build
        run: ctest -V -R java_java_LinearProgramming
        env:
          LD_LIBRARY_PATH: "${{ github.workspace }}/sirius-solver/SiriusInstall/lib/:${{ github.workspace }}/xpressmp813/lib/"
      - name: Run dotnet tests
        id: dotnet_tests
        continue-on-error: true
        working-directory: ./or-tools/build
        run: ctest -V -R dotnet_dotnet_cslinearprogramming
        env:
          LD_LIBRARY_PATH: "${{ github.workspace }}/sirius-solver/SiriusInstall/lib/:${{ github.workspace }}/xpressmp813/lib/"
      - name: Check test results
        run: |
          echo "sirius_interface_unittests: ${{ steps.sirius_interface_unittests.outcome }}"
          echo "xpress_interface_unittests: ${{ steps.xpress_interface_unittests.outcome }}"
          echo "cpp_tests: ${{ steps.cpp_tests.outcome }}"
          echo "python_tests: ${{ steps.python_tests.outcome }}"
          echo "java_tests: ${{ steps.java_tests.outcome }}"
          echo "dotnet_tests: ${{ steps.dotnet_tests.outcome }}"
          [[ "${{ steps.sirius_interface_unittests.outcome }}" == "success" &&
             "${{ steps.xpress_interface_unittests.outcome }}" == "success" &&
             "${{ steps.cpp_tests.outcome }}"                  == "success" &&
             "${{ steps.python_tests.outcome }}"               == "success" &&
             "${{ steps.java_tests.outcome }}"                 == "success" &&
             "${{ steps.dotnet_tests.outcome }}"               == "success" ]]
