name: CMake Docker

on: [push, pull_request]

jobs:
  Distros:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [alpine, archlinux, centos, debian, fedora, opensuse, ubuntu]
        lang: [cpp, python, dotnet, java]
      fail-fast: false
    env:
      DISTRO: ${{ matrix.distro }}
      LANG: ${{ matrix.lang }}
    steps:
    - uses: actions/checkout@v2
    - name: Build base image
      run: make --directory=cmake ${DISTRO}_base
    - name: Build env image
      run: make --directory=cmake ${DISTRO}_${LANG}_env
    - name: Build devel image
      run: make --directory=cmake ${DISTRO}_${LANG}_devel
    - name: Build project
      run: make --directory=cmake ${DISTRO}_${LANG}_build
    - name: Test project
      run: make --directory=cmake ${DISTRO}_${LANG}_test

    - name: Build Install env image
      run: make --directory=cmake ${DISTRO}_${LANG}_install_env
    - name: Build Install devel image
      run: make --directory=cmake ${DISTRO}_${LANG}_install_devel
    - name: Build Install
      run: make --directory=cmake ${DISTRO}_${LANG}_install_build
    - name: Test Install
      run: make --directory=cmake ${DISTRO}_${LANG}_install_test
