name: .Net MacOS CI

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  cmake_make:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check cmake
      run: cmake --version
    - name: Swig install
      run: brew install swig
    - name: Check swig
      run: swig -version
    - name: Check dotnet
      run: dotnet --info
    - name: Configure
      run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DBUILD_DOTNET=ON
    - name: Build
      run: cmake --build build --target all -v
    - name: Test
      run: cmake --build build --target test -v
    - name: Install
      run: cmake --build build --target install -v -- DESTDIR=install
  cmake_xcode:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check cmake
      run: cmake --version
    - name: Swig install
      run: brew install swig
    - name: Check swig
      run: swig -version
    - name: Check dotnet
      run: dotnet --info
    - name: Configure
      run: cmake -S. -Bbuild -G "Xcode" -DCMAKE_CONFIGURATION_TYPES=Release -DBUILD_DOTNET=ON
    - name: Build
      run: cmake --build build --config Release --target ALL_BUILD -v
    - name: Test
      run: cmake --build build --config Release --target RUN_TESTS -v
    - name: Install
      run: cmake --build build --config Release --target install -v
