name: Java Windows CI

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  cmake:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check cmake
      run: cmake --version
    - name: Install swig
      run: |
        (New-Object System.Net.WebClient).DownloadFile("http://prdownloads.sourceforge.net/swig/swigwin-4.0.1.zip","swigwin-4.0.1.zip");
        Expand-Archive .\swigwin-4.0.1.zip .;
        echo "::add-path::./swigwin-4.0.1"
    - name: Check swig
      run: swig -version
    - name: Check java
      run: java -version
    - name: Configure
      run: cmake -S. -Bbuild -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DBUILD_JAVA=ON -DBUILD_DEPS=ON
    - name: Build
      run: cmake --build build --config Release --target ALL_BUILD -- /maxcpucount
    - name: Test
      run: cmake --build build --config Release --target RUN_TESTS -- /maxcpucount
    - name: Install
      run: cmake --build build --config Release --target INSTALL -- /maxcpucount
